'use client';

import React, { useState } from 'react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
  DialogClose,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { useData } from '@/context/data-context';
import { useToast } from '@/hooks/use-toast';
import { PlusCircle, Sparkles, Loader2 } from 'lucide-react';
import { generateProductDescription } from '@/ai/flows/product-descriptor';

interface AddProductModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export function AddProductModal({ open, onOpenChange }: AddProductModalProps) {
  const { addProduct, categories, suppliers } = useData();
  const { toast } = useToast();

  const [description, setDescription] = useState('');
  const [isGeneratingDescription, setIsGeneratingDescription] = useState(false);
  const [name, setName] = useState('');

  const handleAIDescription = async () => {
    if (!name) {
      toast({
        variant: 'destructive',
        title: 'Missing Name',
        description: 'Please enter a product name first.',
      });
      return;
    }
    setIsGeneratingDescription(true);
    try {
      const desc = await generateProductDescription(name);
      setDescription(desc);
      toast({ title: 'AI Description Generated', description: 'Product description generated by AI.' });
    } catch (err) {
      console.error('AI Description error:', err);
    } finally {
      setIsGeneratingDescription(false);
    }
  };

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const formData = new FormData(e.currentTarget);

    const productData = {
      name: formData.get('name') as string,
      sku: (formData.get('sku') as string) || ('SKU-' + Date.now().toString(36).toUpperCase()),
      barcode: (formData.get('barcode') as string) || '',
      brand: (formData.get('brand') as string) || '',
      stock: Number(formData.get('stock')) || 0,
      minStock: Number(formData.get('minStock')) || 5,
      maxStock: Number(formData.get('maxStock')) || 100,
      unit: (formData.get('unit') as string) || 'Piece',
      status: (formData.get('status') as any) || 'Active',
      price: Number(formData.get('price')) || 0,
      costPrice: Number(formData.get('costPrice')) || 0,
      averageDailySales: 1.0,
      leadTimeDays: 7,
      categoryId: (formData.get('categoryId') as string) || '',
      supplierId: (formData.get('supplierId') as string) || '',
      supplier: suppliers.find(s => s.id === formData.get('supplierId'))?.name || '',
      imageUrl: `https://picsum.photos/seed/${Date.now()}/400/400`,
      description: description,
    };

    addProduct(productData);
    toast({ title: 'Product Created', description: `"${productData.name}" added to inventory.` });
    onOpenChange(false);
    setName('');
    setDescription('');
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="w-[95vw] sm:max-w-xl max-h-[90vh] overflow-y-auto ios-glass p-6">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2 text-lg font-bold">
            <PlusCircle className="w-5 h-5 text-primary" />
            Quick Add Product
          </DialogTitle>
          <DialogDescription className="text-xs">
            Add a new product directly from your Command Center.
          </DialogDescription>
        </DialogHeader>

        <form onSubmit={handleSubmit} className="grid gap-4 py-3 text-xs">
          <div className="grid grid-cols-1 sm:grid-cols-4 items-center gap-2">
            <Label htmlFor="qp-name" className="text-left sm:text-right font-medium">Product Name *</Label>
            <Input
              id="qp-name"
              name="name"
              value={name}
              onChange={(e) => setName(e.target.value)}
              placeholder="e.g. Premium Cotton Shirt"
              required
              className="sm:col-span-3 rounded-xl"
            />
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-4 items-center gap-2">
            <Label htmlFor="qp-sku" className="text-left sm:text-right font-medium">SKU Code</Label>
            <Input
              id="qp-sku"
              name="sku"
              placeholder="Auto-generated if blank"
              className="sm:col-span-3 rounded-xl font-mono text-xs"
            />
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-4 items-center gap-2">
            <Label htmlFor="qp-price" className="text-left sm:text-right font-medium">Selling Price *</Label>
            <Input
              id="qp-price"
              name="price"
              type="number"
              step="0.01"
              placeholder="0.00"
              required
              className="sm:col-span-3 rounded-xl"
            />
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-4 items-center gap-2">
            <Label htmlFor="qp-cost" className="text-left sm:text-right font-medium">Cost Price *</Label>
            <Input
              id="qp-cost"
              name="costPrice"
              type="number"
              step="0.01"
              placeholder="0.00"
              required
              className="sm:col-span-3 rounded-xl"
            />
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-4 items-center gap-2">
            <Label htmlFor="qp-stock" className="text-left sm:text-right font-medium">Stock Qty *</Label>
            <Input
              id="qp-stock"
              name="stock"
              type="number"
              defaultValue="10"
              required
              className="sm:col-span-3 rounded-xl"
            />
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-4 items-center gap-2">
            <Label htmlFor="qp-unit" className="text-left sm:text-right font-medium">Unit</Label>
            <Select name="unit" defaultValue="Piece">
              <SelectTrigger className="sm:col-span-3 rounded-xl">
                <SelectValue placeholder="Select unit" />
              </SelectTrigger>
              <SelectContent>
                {['Piece', 'Kg', 'Gram', 'Liter', 'Milliliter', 'Meter', 'Box', 'Pack', 'Bottle', 'Pair', 'Set', 'Custom'].map((u) => (
                  <SelectItem key={u} value={u}>
                    {u}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-4 items-start gap-2">
            <div className="sm:text-right pt-2 flex flex-col items-end gap-1">
              <Label htmlFor="qp-desc" className="font-medium">Description</Label>
              <Button
                type="button"
                variant="ghost"
                size="sm"
                onClick={handleAIDescription}
                disabled={isGeneratingDescription}
                className="h-6 px-2 text-[10px] text-primary gap-1"
              >
                {isGeneratingDescription ? <Loader2 className="w-3 h-3 animate-spin" /> : <Sparkles className="w-3 h-3" />}
                AI
              </Button>
            </div>
            <Textarea
              id="qp-desc"
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              placeholder="Product summary..."
              className="sm:col-span-3 rounded-xl min-h-[80px]"
            />
          </div>

          <DialogFooter className="pt-3">
            <DialogClose asChild>
              <Button type="button" variant="secondary" className="rounded-xl">Cancel</Button>
            </DialogClose>
            <Button type="submit" className="rounded-xl bg-primary text-primary-foreground">Save Product</Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}
